name: Docker Image CI

on: ["push"]

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.1"

      - name: Update repos
        run: sudo apt update

      - name: Install mingw for windows dll tests
        run: sudo apt install -y gcc-mingw-w64

      - name: Make integration tests
        run: yes | make e2e

      - name: Run tests
        working-directory: e2e
        run: ./e2e
    
  build:
    needs: e2e_tests
    if: contains(github.ref, 'refs/tags/v[0-9]+.[0-9]+.[0-9]+')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: reversessh
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: reversessh/reverse_ssh:latest
          push: true
